"""empty message

Revision ID: 3c93c137be4b
Revises: 71977c16ee5a
Create Date: 2026-09-05 14:44:26.893408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c93c137be4b'
down_revision: Union[str, Sequence[str], None] = '71977c16ee5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'messaged_at',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'messaged_at',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
