"""empty message

Revision ID: 4291dac9660b
Revises: f1f9cbe736f2
Create Date: 2026-09-06 13:32:28.713143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4291dac9660b'
down_revision: Union[str, Sequence[str], None] = 'f1f9cbe736f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('Result', sa.Enum('accepted', 'ignored', 'rejected', name='result'), nullable=True))
    op.drop_column('clients', 'result')
    op.drop_constraint(op.f('messages_client_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('notes_client_id_fkey'), 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.add_column('projects', sa.Column('client_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'projects', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'client_id')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key(op.f('notes_client_id_fkey'), 'notes', 'clients', ['client_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_client_id_fkey'), 'messages', 'clients', ['client_id'], ['id'])
    op.add_column('clients', sa.Column('result', postgresql.ENUM('accepted', 'ignored', 'rejected', name='result'), autoincrement=False, nullable=True))
    op.drop_column('clients', 'Result')
    # ### end Alembic commands ###
