"""empty message

Revision ID: 71977c16ee5a
Revises: b7163d26e77b
Create Date: 2026-09-05 14:39:34.007400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71977c16ee5a'
down_revision: Union[str, Sequence[str], None] = 'b7163d26e77b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('google_places_api', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'clients', ['google_places_api'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_column('clients', 'google_places_api')
    # ### end Alembic commands ###
