"""empty message

Revision ID: 9dd048699017
Revises: 3c93c137be4b
Create Date: 2026-09-05 17:11:28.224166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd048699017'
down_revision: Union[str, Sequence[str], None] = '3c93c137be4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('google_places_id', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('website', sa.String(), nullable=True))
    op.drop_constraint(op.f('clients_google_places_api_key'), 'clients', type_='unique')
    op.create_unique_constraint(None, 'clients', ['google_places_id'])
    op.drop_column('clients', 'google_places_api')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('google_places_api', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'clients', type_='unique')
    op.create_unique_constraint(op.f('clients_google_places_api_key'), 'clients', ['google_places_api'], postgresql_nulls_not_distinct=False)
    op.drop_column('clients', 'website')
    op.drop_column('clients', 'google_places_id')
    # ### end Alembic commands ###
